### ISSUE TITLE
The testsuite doesn't do a full print/parse/print round trip.

### ISSUE THREAD

**Issue by Lemmih** [llvm-hs/llvm-hs-pretty#43]
The test suite doesn't check if the pretty-printed IR code matches the original code. As such, it only checks that the pretty-printer generates syntactically valid code.

I tried changing it to do a full round trip but this was easier said than done. Converting between a C++ module and a Haskell module changes things slightly (metadata gets shuffled, etc) which makes it difficult to verify that (parse.print) = id.

**Comment by sdiehl** [comment]
Indeed there are all sorts of subtle behavior with the C++  pretty printer shifting and sorting metadata internally according to sorts on it's classes that are hard to reconstruct. 

If you can come up with an edge case where the syntax isn't fairly represented semantically between printing and parsing feel free to submit a bug report, but we don't currently support what you're asking for in its general form because it's really hard.

**Comment by Lemmih** [comment]
Oh, this issue was not meant as a bug report, just as a reminder for anyone who'll look at the testsuite in the future.

As it is right now, the testsuite only checks for syntax errors in the generated code. It does not check whether the printed code is semantically the same as the parsed code. Since most bugs and typos still leads to syntactically valid code, the testsuite is a lot less powerful than it would appear. This issue is simply a reminder as well as a description of why it's difficult to improve.
